name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best describes the bug.
      options:
        - Setup/Installation
        - Mapping
        - Segmentation
        - Clustering
        - Annotation
        - Visualization
        - Docker
        - Singularity
        - ImageStudio
        - Other
    validations:
      required: true
  - type: dropdown
    id: saw-version
    attributes:
      label: SAW Version
      description: Select the SAW version you are using.
      options:
        - v7.1.2
        - v7.0.1
        - v6.1.4
        - v6.0.2
        - v5.5.4 or older
        - Unsure
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Provide any relevant background information or context about the bug.
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: A description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: media
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
