name: Feedback
description: Provide feedback to help us improve
title: "[Feedback] "
labels: ["Feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide feedback!
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best describes your feedback.
      options:
        - Setup/Installation
        - Mapping
        - Segmentation
        - Clustering
        - Annotation
        - Visualization
        - Docker
        - Singularity
        - ImageStudio
        - Other
    validations:
      required: true
  - type: dropdown
    id: saw-version
    attributes:
      label: SAW Version
      description: Select the SAW version you are using, if applicable.
      options:
        - v7.1.2
        - v7.0.1
        - v6.1.4
        - v6.0.2
        - v5.5.4 or older
        - Unsure
        - Not Applicable
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please provide your feedback.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or details that might help us understand your feedback.
    validations:
      required: false
